//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVM_2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creneau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Creneau()
        {
            this.Reserve1 = new HashSet<Reserve>();
        }

        public Creneau(DateTime p_date)
        {
            date = p_date;
        }
    
        public Creneau(int p_id_creneau, DateTime p_date, bool p_disponibilite, bool p_reserve, int p_id_patient)
        {
            id_creneau = p_id_creneau;
            date = p_date;
            disponibilite = p_disponibilite;
            reserve = p_reserve;
            id_patient = p_id_patient;
        }
        public int id_creneau { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> disponibilite { get; set; }
        public Nullable<bool> reserve { get; set; }
        public Nullable<int> id_patient { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserve> Reserve1 { get; set; }
    }
}
