IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'IIS APPPOOL\HVM')
BEGIN
    CREATE LOGIN [IIS APPPOOL\HVM] 
      FROM WINDOWS WITH DEFAULT_DATABASE=[C:\USERS\SOKAII\SOURCE\REPOS\HVM\HVM\HVM 2.0\APP_DATA\DATABASE1.MDF], 
      DEFAULT_LANGUAGE=[us_english]
END
GO
CREATE USER [HVM] 
  FOR LOGIN [IIS APPPOOL\HVM]
GO
EXEC sp_addrolemember 'db_owner', HVM
GO